/* DrawVerse C ABI. Query paint_core_version and capabilities before use.
 * Initialize struct_size. All buffer lengths are bytes.
 * Model computation, lifecycle, and large pixel copies run off the UI thread.
 * Handles must never be dereferenced. Session submission/polling copies only bounded data.
 * Callbacks must not throw. See contracts/abi.md for ownership/thread/pointer contracts. */

#ifndef DRAWVERSE_PAINT_API_H
#define DRAWVERSE_PAINT_API_H

/* Generated by pinned cbindgen. DO NOT EDIT. See contracts/abi.md. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define PAINT_ABI_MAJOR 1

#define PAINT_ABI_MINOR 12

#define PAINT_ABI_PATCH 0

#define PAINT_COMMAND_ADD_LAYER 8

#define PAINT_COMMAND_ADD_MASK 13

#define PAINT_COMMAND_BEGIN_STROKE 2

#define PAINT_COMMAND_CANCEL_STROKE 5

#define PAINT_COMMAND_END_STROKE 4

#define PAINT_COMMAND_LAYER_PROPERTIES 11

#define PAINT_COMMAND_NEW_DOCUMENT 1

/**
 * ABI 1.6 additive command kinds; old NEW_DOCUMENT remains transparent.
 */
#define PAINT_COMMAND_NEW_WHITE_DOCUMENT 12

#define PAINT_COMMAND_REDO 7

#define PAINT_COMMAND_REMOVE_LAYER 9

#define PAINT_COMMAND_SELECT_LAYER 10

#define PAINT_COMMAND_STROKE_TO 3

#define PAINT_COMMAND_UNDO 6

#define PAINT_EVENT_DOCUMENT_CHANGED 1

#define PAINT_EVENT_DOCUMENT_STATE_CHANGED 2

#define PAINT_FEATURE_ASYNC_SESSION 16

#define PAINT_FEATURE_CLIPPING 2048

#define PAINT_FEATURE_CPU_VIEWPORT 32

#define PAINT_FEATURE_DOCUMENT 1

#define PAINT_FEATURE_EVENTS 8

#define PAINT_FEATURE_FILE_IO 64

#define PAINT_FEATURE_HISTORY 2

#define PAINT_FEATURE_LAYER_APPEARANCE 256

#define PAINT_FEATURE_LAYER_GROUPS 512

#define PAINT_FEATURE_LINEAR_TILE_READ 4

#define PAINT_FEATURE_MASKS 1024

#define PAINT_FEATURE_SELECTION 4096

#define PAINT_FEATURE_STORAGE_SETTINGS 128

#define PAINT_FILE_AUTO 0

#define PAINT_FILE_CANCELLED 5

#define PAINT_FILE_FAILED 4

#define PAINT_FILE_JPEG 2

#define PAINT_FILE_OPEN 1

#define PAINT_FILE_OPENRASTER 4

#define PAINT_FILE_PNG 1

#define PAINT_FILE_QUEUED 1

#define PAINT_FILE_RUNNING 2

#define PAINT_FILE_SAVE 2

#define PAINT_FILE_SUCCEEDED 3

#define PAINT_FILE_WEBP 3

#define PAINT_GROUP_REPARENT 3

#define PAINT_GROUP_UNGROUP 2

#define PAINT_GROUP_WRAP 1

#define PAINT_HISTORY_ADD_LAYER 7

#define PAINT_HISTORY_BRUSH 1

#define PAINT_HISTORY_CLIPPING 18

#define PAINT_HISTORY_DESELECT 5

#define PAINT_HISTORY_ELLIPSE_SELECTION 20

#define PAINT_HISTORY_ERASER 2

#define PAINT_HISTORY_GROUP 14

#define PAINT_HISTORY_INITIAL 0

#define PAINT_HISTORY_INVERT_SELECTION 6

/**
 * ABI 1.12: freehand lasso path and magic-wand region.
 */
#define PAINT_HISTORY_LASSO_SELECTION 21

#define PAINT_HISTORY_LAYER_BLEND 10

#define PAINT_HISTORY_LAYER_FILL 11

#define PAINT_HISTORY_LAYER_LOCKS 12

#define PAINT_HISTORY_LAYER_PROPERTIES 9

#define PAINT_HISTORY_MAGIC_SELECTION 22

#define PAINT_HISTORY_MASK 17

#define PAINT_HISTORY_MOVE_LAYER 13

/**
 * Automatic release of clipped layers whose base went away.
 */
#define PAINT_HISTORY_RELEASE_CLIPPING 23

#define PAINT_HISTORY_REMOVE_LAYER 8

#define PAINT_HISTORY_REPARENT 16

#define PAINT_HISTORY_SELECTION 4

#define PAINT_HISTORY_SELECT_ALL 3

#define PAINT_HISTORY_TRUNCATED 19

#define PAINT_HISTORY_UNGROUP 15

#define PAINT_INPUT_BUTTONS 16

#define PAINT_INPUT_PRESSURE 1

#define PAINT_INPUT_ROTATION 4

#define PAINT_INPUT_TANGENTIAL_PRESSURE 8

#define PAINT_INPUT_TILT 2

#define PAINT_LAYER_GROUP 1

#define PAINT_LAYER_MASK 2

#define PAINT_LAYER_PIXEL 0

#define PAINT_LOCK_ALL 4

#define PAINT_LOCK_POSITION 2

#define PAINT_LOCK_TRANSPARENCY 1

#define PAINT_MODE_ERASE 2

#define PAINT_MODE_PAINT 1

#define PAINT_SELECTION_ADD 1

#define PAINT_SELECTION_ALL 2

#define PAINT_SELECTION_CLEAR 1

#define PAINT_SELECTION_ELLIPSE 1

#define PAINT_SELECTION_INTERSECT 3

#define PAINT_SELECTION_INVERT 3

#define PAINT_SELECTION_MASK 3

/**
 * ABI 1.12: content-derived selection edits.
 */
#define PAINT_SELECTION_PATH_MAGIC 1

/**
 * ABI 1.12: rasterized shapes. The geometry fields stay the bounding box for old callers.
 */
#define PAINT_SELECTION_POLYGON 2

#define PAINT_SELECTION_RECTANGLE 0

#define PAINT_SELECTION_REPLACE 0

#define PAINT_SELECTION_SHAPE 0

#define PAINT_SELECTION_STEP_INVERT 4

#define PAINT_SELECTION_SUBTRACT 2

#define PAINT_SESSION_FAILED 4

#define PAINT_SESSION_MODIFIED 2

#define PAINT_SESSION_RUNNING 1

#define PAINT_STORAGE_RGBA32F_PREMULTIPLIED 1

#define PAINT_TILE_RGBA32F_LINEAR_PREMULTIPLIED 2

#define PAINT_TILE_RGBA8_SRGB_PREMULTIPLIED 3

#define PAINT_TOOL_ERASER 2

#define PAINT_TOOL_MOUSE 3

#define PAINT_TOOL_PEN 1

#define PAINT_WORKING_LINEAR_SRGB 1

typedef struct PaintCore PaintCore;

typedef struct PaintDocument PaintDocument;

typedef struct PaintSession PaintSession;

typedef struct PaintSubscription PaintSubscription;

typedef int32_t PaintStatus;

typedef struct PaintStrokeDesc {
  uint32_t struct_size;
  uint32_t mode;
  uint64_t layer_id;
  float radius;
  float opacity;
  float spacing;
  float linear_rgba[4];
  uint32_t reserved[3];
} PaintStrokeDesc;

typedef struct PaintPoint {
  uint32_t struct_size;
  uint32_t capabilities;
  double x;
  double y;
  float pressure;
  float tilt_x;
  float tilt_y;
  float rotation;
  float tangential_pressure;
  uint32_t buttons;
  uint32_t tool;
  uint64_t timestamp_ns;
} PaintPoint;

typedef struct PaintCapabilities {
  uint32_t struct_size;
  uint32_t abi_major;
  uint64_t features;
  uint32_t max_dimension;
  uint32_t tile_size;
  uint32_t max_read_tile_edge;
  uint32_t reserved;
} PaintCapabilities;

/**
 * ABI 1.3: zero path_length selects the system temp directory. Other fields are explicit.
 */
typedef struct PaintStorageOptions {
  uint32_t struct_size;
  uint32_t reserved;
  const uint8_t *path;
  uint64_t path_length;
  uint64_t resident_bytes;
  uint64_t scratch_bytes;
  uint64_t min_free_bytes;
} PaintStorageOptions;

typedef struct PaintDocumentDesc {
  uint32_t struct_size;
  uint32_t width;
  uint32_t height;
  uint32_t working_space;
  uint32_t pixel_format;
  uint32_t reserved[3];
} PaintDocumentDesc;

/**
 * data/capacity/stride/format are inputs. Other fields are filled after complete copying.
 */
typedef struct PaintTile {
  uint32_t struct_size;
  uint32_t format;
  uint8_t *data;
  uint64_t capacity;
  uint64_t stride;
  uint64_t required;
  uint32_t width;
  uint32_t height;
  uint64_t revision;
} PaintTile;

typedef struct PaintEvent {
  uint32_t struct_size;
  uint32_t kind;
  uint64_t document_id;
  uint64_t revision;
  uint64_t task_id;
  int32_t x;
  int32_t y;
  uint32_t width;
  uint32_t height;
  PaintStatus status;
  uint32_t reserved;
} PaintEvent;

/**
 * Borrowed event, valid only for the callback. Copy before queuing to a UI thread.
 */
typedef void (*PaintEventCallback)(const struct PaintEvent*, void*);

typedef struct PaintVersion {
  uint32_t struct_size;
  uint32_t major;
  uint32_t minor;
  uint32_t patch;
} PaintVersion;

typedef struct PaintDocumentInfo {
  uint32_t struct_size;
  uint32_t width;
  uint32_t height;
  uint32_t layer_count;
  uint64_t document_id;
  uint64_t active_layer_id;
  uint64_t revision;
  uint64_t allocated_tiles;
  uint32_t undo_depth;
  uint32_t redo_depth;
  uint32_t stroke_active;
  uint32_t reserved;
} PaintDocumentInfo;

typedef struct PaintLayerInfo {
  uint32_t struct_size;
  uint32_t visible;
  uint64_t layer_id;
  float opacity;
  uint32_t reserved;
  uint64_t name_length;
  uint64_t allocated_tiles;
} PaintLayerInfo;

/**
 * placement: 0=inside group/root, 1=above sibling, 2=below sibling.
 */
typedef struct PaintLayerDrop {
  uint32_t struct_size;
  uint32_t placement;
  uint64_t layer_id;
  uint64_t target_id;
} PaintLayerDrop;

typedef struct PaintSelectionEdit {
  uint32_t struct_size;
  uint32_t action;
  uint32_t operation;
  uint32_t shape;
  uint32_t antialias;
  uint32_t reserved[3];
  double x;
  double y;
  double width;
  double height;
} PaintSelectionEdit;

/**
 * ABI 1.12: the seed point of a content-derived selection, in document pixels.
 */
typedef struct PaintSelectionPoint {
  double x;
  double y;
} PaintSelectionPoint;

/**
 * ABI 1.12: a freehand path (lasso) or a seed point (magic wand) with tolerance.
 */
typedef struct PaintSelectionPath {
  uint32_t struct_size;
  uint32_t edit_kind;
  uint32_t operation;
  uint32_t antialias;
  uint32_t point_count;
  uint32_t tolerance;
  uint32_t reserved[2];
  const struct PaintSelectionPoint *points;
} PaintSelectionPath;

typedef struct PaintFileJobInfo {
  uint32_t struct_size;
  uint32_t state;
  uint64_t job_id;
  uint64_t source_generation;
  uint64_t source_revision;
  uint64_t result_generation;
  uint64_t result_revision;
  uint32_t kind;
  uint32_t format;
  PaintStatus status;
  uint32_t reserved;
} PaintFileJobInfo;

/**
 * ABI 1.2: UTF-8 OS path, copied before returning; not a file URL.
 */
typedef struct PaintFileRequest {
  uint32_t struct_size;
  uint32_t kind;
  uint32_t format;
  uint32_t quality;
  const uint8_t *path;
  uint64_t path_length;
  uint64_t document_generation;
  float linear_background[4];
  uint32_t reserved[2];
} PaintFileRequest;

typedef struct PaintFrameInfo {
  uint32_t struct_size;
  uint32_t format;
  uint64_t document_generation;
  uint64_t revision;
  uint64_t request_id;
  uint64_t frame_id;
  uint32_t pixel_width;
  uint32_t pixel_height;
  double x;
  double y;
  double width;
  double height;
  uint64_t required_bytes;
  uint64_t reserved;
} PaintFrameInfo;

/**
 * WRAP copies a UTF-8 name; REPARENT uses parent_id (0=root); UNGROUP uses neither.
 */
typedef struct PaintGroupRequest {
  uint32_t struct_size;
  uint32_t kind;
  uint64_t layer_id;
  uint64_t parent_id;
  const uint8_t *name;
  uint64_t name_length;
} PaintGroupRequest;

/**
 * ABI 1.10: metadata for one retained history boundary/operation.
 */
typedef struct PaintHistoryEntry {
  uint32_t struct_size;
  uint32_t kind;
  uint32_t depth;
  uint32_t reserved;
} PaintHistoryEntry;

typedef struct PaintSessionInfo {
  uint32_t struct_size;
  uint32_t flags;
  uint64_t document_generation;
  uint64_t publication;
  uint64_t completed_sequence;
  uint64_t revision;
  uint64_t active_layer_id;
  uint64_t last_error_sequence;
  uint32_t width;
  uint32_t height;
  uint32_t layer_count;
  uint32_t undo_depth;
  uint32_t redo_depth;
  uint32_t stroke_active;
  uint32_t queue_length;
  PaintStatus last_error_status;
  uint64_t reserved[2];
} PaintSessionInfo;

/**
 * ABI 1.4; replaces no prior DTO. fill is independent of opacity; offsets are document pixels.
 */
typedef struct PaintLayerAppearance {
  uint32_t struct_size;
  uint32_t locks;
  uint32_t blend_mode;
  uint32_t reserved;
  float fill;
  int32_t offset_x;
  int32_t offset_y;
  uint32_t dissolve_seed;
} PaintLayerAppearance;

/**
 * ABI 1.7 additive clipping query/edit. base_layer_id is query-only (0 if orphaned).
 */
typedef struct PaintLayerClipping {
  uint32_t struct_size;
  uint32_t enabled;
  uint64_t base_layer_id;
} PaintLayerClipping;

/**
 * ABI 1.5: independent hierarchy metadata; no existing DTO changes.
 */
typedef struct PaintLayerHierarchy {
  uint32_t struct_size;
  uint32_t kind;
  uint64_t parent_id;
  uint32_t depth;
  uint32_t effective_locks;
} PaintLayerHierarchy;

typedef struct PaintSelectionInfo {
  uint32_t struct_size;
  uint32_t enabled;
  uint32_t step_count;
  uint32_t reserved;
} PaintSelectionInfo;

typedef struct PaintSelectionStep {
  uint32_t struct_size;
  uint32_t operation;
  uint32_t shape;
  uint32_t antialias;
  double x;
  double y;
  double width;
  double height;
} PaintSelectionStep;

typedef struct PaintViewport {
  uint32_t struct_size;
  uint32_t view_id;
  uint32_t enabled;
  uint32_t reserved;
  double x;
  double y;
  double width;
  double height;
  uint32_t pixel_width;
  uint32_t pixel_height;
  uint64_t document_generation;
} PaintViewport;

/**
 * ABI 1.1 asynchronous command. Only fields used by kind are read; reserved is zero.
 */
typedef struct PaintCommand {
  uint32_t struct_size;
  uint32_t kind;
  struct PaintStrokeDesc stroke;
  struct PaintPoint point;
  uint64_t layer_id;
  const uint8_t *text;
  uint64_t text_length;
  uint32_t width;
  uint32_t height;
  uint32_t visible;
  float opacity;
  uint32_t reserved[2];
} PaintCommand;

typedef struct PaintStorageInfo {
  uint32_t struct_size;
  uint32_t removed_runs;
  uint64_t available_bytes;
  uint64_t removed_bytes;
  uint32_t skipped_runs;
  uint32_t reserved;
} PaintStorageInfo;

#define PAINT_BUFFER_TOO_SMALL 10

#define PAINT_BUSY 3

#define PAINT_CANCELLED 7

#define PAINT_INTERNAL_ERROR 9

#define PAINT_INVALID_ARGUMENT 1

#define PAINT_INVALID_HANDLE 2

#define PAINT_IO_ERROR 8

#define PAINT_LAYER_LOCKED 11

#define PAINT_LIMIT_EXCEEDED 5

#define PAINT_NOT_FOUND 4

#define PAINT_OK 0

#define PAINT_UNSUPPORTED 6

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Begin one undoable stroke on desc.layer_id; invalid input preserves active-layer selection.
 * # Safety
 * Follow input struct_size, handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_core_begin_stroke(struct PaintCore *core,
                                    struct PaintDocument *doc,
                                    const struct PaintStrokeDesc *desc,
                                    const struct PaintPoint *first);

/**
 * Roll back the active stroke; no active stroke returns INVALID_ARGUMENT.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_core_cancel_stroke(struct PaintCore *core, struct PaintDocument *doc);

/**
 * Only reports implemented features. No GPU capability is advertised.
 * # Safety
 * Follow the caller-memory and handle contract in contracts/abi.md.
 */
PaintStatus paint_core_capabilities(struct PaintCore *core, struct PaintCapabilities *out_caps);

/**
 * Create an owning core handle; failure writes NULL.
 * # Safety
 * out_core must be writable nonoverlapping pointer storage; see contracts/abi.md.
 */
PaintStatus paint_core_create(struct PaintCore **out_core);

/**
 * ABI 1.3: validate/probe/clean configured scratch space, then create a core. Worker thread only.
 * # Safety
 * Follow initialized DTO, writable output and nonoverlapping UTF-8 contracts in contracts/abi.md.
 */
PaintStatus paint_core_create_with_storage(const struct PaintStorageOptions *options,
                                           struct PaintCore **out_core);

/**
 * BUSY while any document/subscription is alive; success writes NULL; NULL is idempotent.
 * # Safety
 * Valid writable pointer-to-handle; caller must serialize destruction; see contracts/abi.md.
 */
PaintStatus paint_core_destroy(struct PaintCore **core);

/**
 * Commit an active stroke. A no-op stroke succeeds without creating history.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_core_end_stroke(struct PaintCore *core, struct PaintDocument *doc);

/**
 * Create a transparent document with one layer. Failure writes NULL.
 * # Safety
 * Follow caller-memory/struct_size/handle contracts in contracts/abi.md.
 */
PaintStatus paint_core_new_document(struct PaintCore *core,
                                    const struct PaintDocumentDesc *desc,
                                    struct PaintDocument **out_doc);

/**
 * Read normal-composited linear premultiplied RGBA32F, native endian, at most 256x256.
 * Query capacity with data=NULL/capacity=0; initialize format and stride (bytes).
 * # Safety
 * Follow buffer capacities, nonoverlap, struct_size and handle contracts in contracts/abi.md.
 */
PaintStatus paint_core_read_tile(struct PaintCore *core,
                                 struct PaintDocument *doc,
                                 uint32_t x,
                                 uint32_t y,
                                 uint32_t width,
                                 uint32_t height,
                                 struct PaintTile *out_tile);

/**
 * Redo one command; empty history succeeds. BUSY during an active stroke.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_core_redo(struct PaintCore *core, struct PaintDocument *doc);

/**
 * Add an ordered tablet sample. Resource-budget failure may roll back the entire stroke.
 * # Safety
 * Follow input struct_size, handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_core_stroke_to(struct PaintCore *core,
                                 struct PaintDocument *doc,
                                 const struct PaintPoint *sample);

/**
 * Subscribe to pixel/structural and metadata state changes; no initial event is emitted.
 * # Safety
 * Callback and user_data must remain valid until unsubscribe returns; cannot throw/unwind.
 */
PaintStatus paint_core_subscribe(struct PaintCore *core,
                                 PaintEventCallback callback,
                                 void *user_data,
                                 struct PaintSubscription **out_subscription);

/**
 * Undo one command; empty history succeeds. BUSY during an active stroke.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_core_undo(struct PaintCore *core, struct PaintDocument *doc);

/**
 * Disable and drain callbacks; success writes NULL. Forbidden inside a callback (BUSY).
 * # Safety
 * Follow writable pointer-to-handle and serialized destruction contracts in contracts/abi.md.
 */
PaintStatus paint_core_unsubscribe(struct PaintCore *core, struct PaintSubscription **subscription);

/**
 * Query ABI version; out_version.struct_size must be initialized.
 * # Safety
 * Follow the valid, aligned, nonoverlapping caller-memory contract in contracts/abi.md.
 */
PaintStatus paint_core_version(struct PaintVersion *out_version);

/**
 * Release a document (including any uncommitted stroke); success writes NULL.
 * # Safety
 * Follow writable pointer-to-handle and serialized destruction contracts in contracts/abi.md.
 */
PaintStatus paint_document_destroy(struct PaintCore *core, struct PaintDocument **doc);

/**
 * Read metadata without exposing the internal document layout.
 * # Safety
 * Follow output struct_size and pointer/handle contracts in contracts/abi.md.
 */
PaintStatus paint_document_info(struct PaintCore *core,
                                struct PaintDocument *doc,
                                struct PaintDocumentInfo *out_info);

/**
 * Copy the calling thread's last error, without clearing/replacing it. No NUL terminator.
 * # Safety
 * Follow nonoverlapping writable buffer/required and capacity contracts in contracts/abi.md.
 */
PaintStatus paint_error_message(uint8_t *buffer, uint64_t capacity, uint64_t *required);

/**
 * Add a UTF-8-named layer above all existing layers; makes it active. Failure writes ID 0.
 * # Safety
 * Follow UTF-8 length, pointer and handle contracts in contracts/abi.md.
 */
PaintStatus paint_layer_add(struct PaintCore *core,
                            struct PaintDocument *doc,
                            const uint8_t *name,
                            uint64_t name_length,
                            uint64_t *out_id);

/**
 * Enumerate layers bottom-to-top by zero-based index. Invalid index returns NOT_FOUND.
 * # Safety
 * Follow output struct_size and pointer/handle contracts in contracts/abi.md.
 */
PaintStatus paint_layer_info(struct PaintCore *core,
                             struct PaintDocument *doc,
                             uint32_t index,
                             struct PaintLayerInfo *out_info);

/**
 * UTF-8 bytes without NUL. Query with NULL/0; BUFFER_TOO_SMALL returns required bytes.
 * # Safety
 * buffer/required must be valid nonoverlapping writable memory; see contracts/abi.md.
 */
PaintStatus paint_layer_name(struct PaintCore *core,
                             struct PaintDocument *doc,
                             uint64_t layer_id,
                             uint8_t *buffer,
                             uint64_t capacity,
                             uint64_t *required);

/**
 * Remove a layer with undo history; removing the last layer is invalid.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_layer_remove(struct PaintCore *core,
                               struct PaintDocument *doc,
                               uint64_t layer_id);

/**
 * Selection state only; emits a state event, but no undo command or pixel revision.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_layer_set_active(struct PaintCore *core,
                                   struct PaintDocument *doc,
                                   uint64_t layer_id);

/**
 * visible is exactly 0 or 1; opacity is finite in [0,1]. Undoable.
 * # Safety
 * Follow handle and ordered-command contracts in contracts/abi.md.
 */
PaintStatus paint_layer_set_properties(struct PaintCore *core,
                                       struct PaintDocument *doc,
                                       uint64_t layer_id,
                                       uint32_t visible,
                                       float opacity);

/**
 * ABI 1.1: create an owning async document session. Creation/destruction run off the UI thread.
 * # Safety
 * Follow writable output, initialized DTO, and core lifetime contracts in contracts/abi.md.
 */
PaintStatus paint_session_create(struct PaintCore *core,
                                 const struct PaintDocumentDesc *desc,
                                 struct PaintSession **out_session);

/**
 * Stop/cancel/join workers; clear handle after success. Core stays BUSY until sessions are released.
 * # Safety
 * Caller must stop concurrent calls and serialize lifecycle; background thread only.
 */
PaintStatus paint_session_destroy(struct PaintCore *core,
                                  struct PaintSession **handle);

/**
 * ABI 1.6: atomic subtree reorder/reparent; IDs and placement are copied immediately.
 * # Safety
 * Initialize input DTO and provide writable sequence; follow session ownership contract.
 */
PaintStatus paint_session_drop_layer(struct PaintCore *core,
                                     struct PaintSession *session,
                                     const struct PaintLayerDrop *request,
                                     uint64_t *out_sequence);

/**
 * ABI 1.8: enqueue a geometric selection edit, copied and validated before returning.
 * # Safety
 * Initialize request size and writable sequence; follow contracts/abi.md ownership rules.
 */
PaintStatus paint_session_edit_selection(struct PaintCore *core,
                                         struct PaintSession *session,
                                         const struct PaintSelectionEdit *request,
                                         uint64_t *out_sequence);

/**
 * ABI 1.12: enqueue a freehand-path (lasso) or content-derived (magic wand) selection edit.
 * Points are copied and validated before returning; the session resolves the region off the UI thread.
 * # Safety
 * `request` must point to an initialized `PaintSelectionPath`; `points` must be a readable array of
 * `point_count` initialized points; `out_sequence` must be writable.
 */
PaintStatus paint_session_edit_selection_path(struct PaintCore *core,
                                              struct PaintSession *session,
                                              const struct PaintSelectionPath *request,
                                              uint64_t *out_sequence);

/**
 * Read the latest asynchronous execution error. Synchronous submission errors use paint_error_message.
 * # Safety
 * Follow UTF-8 buffer contract; error sequence must match session_info.
 */
PaintStatus paint_session_error_message(struct PaintCore *core,
                                        struct PaintSession *handle,
                                        uint64_t error_sequence,
                                        uint8_t *buffer,
                                        uint64_t capacity,
                                        uint64_t *required);

/**
 * Cooperative cancellation. Successful atomic commits stay successful.
 * # Safety
 * Follow the handle lifetime and serialization contract in contracts/abi.md.
 */
PaintStatus paint_session_file_cancel(struct PaintCore *core,
                                      struct PaintSession *session,
                                      uint64_t job);

/**
 * Query a small retained result without waiting for disk access.
 * # Safety
 * Follow handle and writable initialized DTO contracts in contracts/abi.md.
 */
PaintStatus paint_session_file_info(struct PaintCore *core,
                                    struct PaintSession *session,
                                    uint64_t job,
                                    struct PaintFileJobInfo *out);

/**
 * Copy asynchronous file error text as UTF-8, without a trailing NUL.
 * # Safety
 * Output capacity/required pointers must meet the buffer contract in contracts/abi.md.
 */
PaintStatus paint_session_file_message(struct PaintCore *core,
                                       struct PaintSession *session,
                                       uint64_t job,
                                       uint8_t *buffer,
                                       uint64_t capacity,
                                       uint64_t *required);

/**
 * Queue file IO; at most one job per session. Job ID remains valid until the next submission.
 * # Safety
 * Initialize DTO sizes; UTF-8 path bytes must remain readable for this call only.
 */
PaintStatus paint_session_file_submit(struct PaintCore *core,
                                      struct PaintSession *session,
                                      const struct PaintFileRequest *request,
                                      uint64_t *out_job);

/**
 * Return the latest complete frame. BUSY while pending/disabled. No partial frame is exposed.
 * # Safety
 * Follow initialized output and session lifetime contracts.
 */
PaintStatus paint_session_frame_info(struct PaintCore *core,
                                     struct PaintSession *handle,
                                     uint32_t view_id,
                                     struct PaintFrameInfo *out_info);

/**
 * ABI 1.5: FIFO group operation. Name bytes are copied before return.
 * # Safety
 * Initialize request size, keep name alive for this call and provide writable sequence.
 */
PaintStatus paint_session_group(struct PaintCore *core,
                                struct PaintSession *session,
                                const struct PaintGroupRequest *request,
                                uint64_t *out_sequence);

/**
 * ABI 1.10: read retained operation metadata from the exact publication.
 * Depth zero is INITIAL or TRUNCATED; remaining indices are chronological operations.
 * # Safety
 * Initialize output size and follow session/publication lifetime contracts.
 */
PaintStatus paint_session_history_entry(struct PaintCore *core,
                                        struct PaintSession *handle,
                                        uint64_t expected_publication,
                                        uint32_t index,
                                        struct PaintHistoryEntry *out_entry);

/**
 * Read published immutable metadata; never waits for the document computation lock.
 * # Safety
 * Follow initialized output DTO and session lifetime contracts.
 */
PaintStatus paint_session_info(struct PaintCore *core,
                               struct PaintSession *handle,
                               struct PaintSessionInfo *out_info);

/**
 * ABI 1.4: small immutable layer configuration query, tied to exact publication ID.
 * # Safety
 * Follow initialized output DTO, publication and ownership contracts in contracts/abi.md.
 */
PaintStatus paint_session_layer_appearance(struct PaintCore *core,
                                           struct PaintSession *session,
                                           uint64_t publication,
                                           uint64_t layer_id,
                                           struct PaintLayerAppearance *out);

/**
 * ABI 1.7: publication-consistent clipping flag and resolved same-parent base.
 * # Safety
 * Provide initialized writable DTO; follow publication and handle ownership contracts.
 */
PaintStatus paint_session_layer_clipping(struct PaintCore *core,
                                         struct PaintSession *session,
                                         uint64_t publication,
                                         uint64_t layer_id,
                                         struct PaintLayerClipping *out);

/**
 * ABI 1.5: hierarchy metadata from the same immutable publication as layer_info.
 * # Safety
 * Initialize the output DTO and follow session/publication ownership contracts.
 */
PaintStatus paint_session_layer_hierarchy(struct PaintCore *core,
                                          struct PaintSession *session,
                                          uint64_t publication,
                                          uint64_t layer_id,
                                          struct PaintLayerHierarchy *out);

/**
 * Enumerate bottom-to-top from one exact publication; BUSY means retry the complete enumeration.
 * # Safety
 * Follow initialized output DTO, publication, and session lifetime contracts.
 */
PaintStatus paint_session_layer_info(struct PaintCore *core,
                                     struct PaintSession *handle,
                                     uint64_t expected_publication,
                                     uint32_t index,
                                     struct PaintLayerInfo *out_info);

/**
 * Copy UTF-8 without NUL. NULL/0 capacity query returns required bytes.
 * # Safety
 * Follow nonoverlapping caller buffers and exact publication contract.
 */
PaintStatus paint_session_layer_name(struct PaintCore *core,
                                     struct PaintSession *handle,
                                     uint64_t expected_publication,
                                     uint64_t id,
                                     uint8_t *buffer,
                                     uint64_t capacity,
                                     uint64_t *required);

/**
 * ABI 1.4: integer relative non-destructive content translation, checked by the actor.
 * # Safety
 * Follow writable sequence, session ownership and serialized destruction contracts.
 */
PaintStatus paint_session_move_layer(struct PaintCore *core,
                                     struct PaintSession *session,
                                     uint64_t layer_id,
                                     int32_t dx,
                                     int32_t dy,
                                     uint64_t *out_sequence);

/**
 * Worker-only RGBA8 frame copy. Exact request/frame IDs are required. Padding is not touched.
 * # Safety
 * Follow capacity/stride/nonoverlap contract. No pixels are written until all inputs validate.
 */
PaintStatus paint_session_read_frame(struct PaintCore *core,
                                     struct PaintSession *handle,
                                     uint32_t view_id,
                                     uint64_t request_id,
                                     uint64_t frame_id,
                                     struct PaintTile *out_tile);

/**
 * ABI 1.12: read one pixel of an already rendered viewport for the eyedropper. Read-only: the
 * sample never enters history, never marks dirty tiles and never bumps the revision. Coordinates
 * outside the rendered region are clamped to its edge.
 * # Safety
 * `out_rgba` must be writable for four floats; follow session lifetime contracts.
 */
PaintStatus paint_session_sample_pixel(struct PaintCore *core,
                                       struct PaintSession *handle,
                                       uint32_t view,
                                       int64_t x,
                                       int64_t y,
                                       float *out_rgba);

/**
 * ABI 1.8: query selection summary tied to exactly one immutable publication.
 * # Safety
 * Initialize output size and follow aligned writable memory/handle contracts.
 */
PaintStatus paint_session_selection_info(struct PaintCore *core,
                                         struct PaintSession *session,
                                         uint64_t publication,
                                         struct PaintSelectionInfo *out);

/**
 * ABI 1.8: query one bounded selection step; inversion uses zero geometry.
 * # Safety
 * Initialize output size; index must belong to the same queried publication.
 */
PaintStatus paint_session_selection_step(struct PaintCore *core,
                                         struct PaintSession *session,
                                         uint64_t publication,
                                         uint32_t index,
                                         struct PaintSelectionStep *out);

/**
 * ABI 1.9: non-mutating full composite blend preview in view slot 0/1.
 * A regular set_viewport replaces/clears the override; requests retain normal generation semantics.
 * # Safety
 * Follow initialized viewport, writable output and session lifetime contracts.
 */
PaintStatus paint_session_set_blend_preview(struct PaintCore *core,
                                            struct PaintSession *session,
                                            uint64_t layer_id,
                                            uint32_t blend_mode,
                                            const struct PaintViewport *viewport,
                                            uint64_t *out_request);

/**
 * ABI 1.11: retarget the per-document history command limit. Accepted like a command and applied
 * in order on the session worker; a smaller limit evicts the oldest undo records and the history
 * boundary becomes unreachable (no fake initial state). Returns the accepted sequence.
 * # Safety
 * Follow session lifetime contracts; serialize with other submit calls for this session.
 */
PaintStatus paint_session_set_history_limit(struct PaintCore *core,
                                            struct PaintSession *handle,
                                            uint32_t max_commands,
                                            uint64_t *out_sequence);

/**
 * ABI 1.4: FIFO appearance edit; validate/copy DTO before return, actor enforces locks.
 * # Safety
 * Follow valid initialized input, writable sequence and session ownership contracts.
 */
PaintStatus paint_session_set_layer_appearance(struct PaintCore *core,
                                               struct PaintSession *session,
                                               uint64_t layer_id,
                                               const struct PaintLayerAppearance *options,
                                               uint64_t *out_sequence);

/**
 * ABI 1.7: FIFO clipping edit. base_layer_id must be 0; actor resolves adjacency.
 * # Safety
 * Initialize input DTO and writable sequence; follow session ownership contracts.
 */
PaintStatus paint_session_set_layer_clipping(struct PaintCore *core,
                                             struct PaintSession *session,
                                             uint64_t layer_id,
                                             const struct PaintLayerClipping *options,
                                             uint64_t *out_sequence);

/**
 * ABI 1.4: background raw layer preview using reserved view slot 2 or 3.
 * Read via the existing frame_info/read_frame functions; disable via set_viewport.
 * # Safety
 * Follow initialized input DTO, output sequence and handle ownership contracts.
 */
PaintStatus paint_session_set_layer_preview(struct PaintCore *core,
                                            struct PaintSession *session,
                                            uint64_t layer_id,
                                            const struct PaintViewport *viewport,
                                            uint64_t *out_request);

/**
 * Update one of four output slots without model computation. enabled=0 cancels/releases that view.
 * # Safety
 * Follow initialized viewport, document generation, and nonoverlapping output contracts.
 */
PaintStatus paint_session_set_viewport(struct PaintCore *core,
                                       struct PaintSession *handle,
                                       const struct PaintViewport *viewport,
                                       uint64_t *out_request);

/**
 * Copy a small command into Rust FIFO. OK means accepted, not completed; poll session_info.
 * Layer ID zero in Begin means the active layer at execution time. Overload rolls a stroke back.
 * # Safety
 * Initialize outer/nested DTO sizes, keep text valid for this call, serialize stroke input order.
 */
PaintStatus paint_session_submit(struct PaintCore *core,
                                 struct PaintSession *handle,
                                 const struct PaintCommand *command,
                                 uint64_t *out_sequence);

/**
 * ABI 1.3: inspect a candidate configuration without changing a running core. Worker thread only.
 * Validation creates a writable run and cleans marked unlocked stale runs; no document recovery.
 * # Safety
 * Follow initialized DTO and writable output contracts in contracts/abi.md.
 */
PaintStatus paint_storage_inspect(const struct PaintStorageOptions *options,
                                  struct PaintStorageInfo *out_info);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DRAWVERSE_PAINT_API_H */
